### ISSUE TITLE
Column profiler crashes when column contains lists

### ISSUE THREAD

**Issue by arnov** [whylabs/whylogs#363]
```
Traceback (most recent call last):
  File "/Users/arnov/Documents/code/project/src/utils/monitoring.py", line 20, in log_dataframe
    ylog.log_dataframe(df)
  File "/Users/arnov/.pyenv/versions/imputations/lib/python3.8/site-packages/whylogs/app/logger.py", line 569, in log_dataframe
    self._profiles[-1]["full_profile"].track_dataframe(df)
  File "/Users/arnov/.pyenv/versions/imputations/lib/python3.8/site-packages/whylogs/core/datasetprofile.py", line 293, in track_dataframe
    self.track(col_str, xi, character_list=None, token_method=None)
  File "/Users/arnov/.pyenv/versions/imputations/lib/python3.8/site-packages/whylogs/core/datasetprofile.py", line 229, in track
    self.track_datum(columns, data)
  File "/Users/arnov/.pyenv/versions/imputations/lib/python3.8/site-packages/whylogs/core/datasetprofile.py", line 247, in track_datum
    prof.track(data, character_list=None, token_method=None)
  File "/Users/arnov/.pyenv/versions/imputations/lib/python3.8/site-packages/whylogs/core/columnprofile.py", line 109, in track
    if pd.isnull(value):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

The column looks like this:

```
df['codes']
0       [6420, 68204, 68203, 6832, 6810]
1                                 [6630]
2                          [4726, 47789]
3             [6420, 70102, 66292, 6612]
4             [6420, 70102, 64923, 6612]
                     ...
696                               [6420]
697    [6420, 70102, 64923, 70101, 6612]
698                              [70221]
699                        [49391, 4932]
700                [47713, 47712, 47711]
Name: codes, Length: 701, dtype: object
```

The problem is that pd.isnull() evaluates for each element of the list, and `if` tries to convert that to one boolean, which doesn't work

**Comment by jamie256** [comment]
Thanks for the details, this was very helpful, I will get a small fix for this to not throw and release updated release with a fix.
