### ISSUE TITLE
Segmenting on one integer-type column throws error, but on two it doesn't 

### ISSUE THREAD

**Issue by FelipeAdachi** [whylabs/whylogs#502]
### Summary

When segmenting on an integer column `col2` with categories `[1,2]`, a `TypeError` is raised.

But when segmenting two integer-type columns, adding `col3` with categories `[100,200`] it doesn't break.
See example below

whylogs version 0.7.1

### Example

Running:

```python
import pandas as pd
from whylogs import get_or_create_session

data = {"col1": ["cats", "dogs", "deers", "cats"], "col2": [1, 2, 1, 2], "col3": [100, 100, 200, 100]}


df = pd.DataFrame(data)

print(df.head())


sess = get_or_create_session()

with sess.logger(dataset_name="my_dataset") as logger:
    logger.log_dataframe(df, segments=["col2"])
    prof_seg = logger.segmented_profiles
```

The following error is raised:

```
Traceback (most recent call last):
  File "/mnt/c/Users/felip/OneDrive/Documentos/Projects/whylogs-felipeadachi/examples/segmentation/demo_test.py", line 16, in <module>
    logger.log_dataframe(df, segments=["col2"])
  File "/home/felipeadachi/miniconda3/lib/python3.8/site-packages/whylogs/app/logger.py", line 617, in log_dataframe
    self.log_segments(df)
  File "/home/felipeadachi/miniconda3/lib/python3.8/site-packages/whylogs/app/logger.py", line 622, in log_segments
    self.log_segments_keys(data)
  File "/home/felipeadachi/miniconda3/lib/python3.8/site-packages/whylogs/app/logger.py", line 642, in log_segments_keys
    segment_tags = [
  File "/home/felipeadachi/miniconda3/lib/python3.8/site-packages/whylogs/app/logger.py", line 643, in <listcomp>
    {"key": self.segments[i], "value": each_segment[i]}
TypeError: 'int' object is not subscriptable
```

When running the following code:

```python
import pandas as pd
from whylogs import get_or_create_session

data = {"col1": ["cats", "dogs", "deers", "cats"], "col2": [1, 2, 1, 2], "col3": [100, 100, 200, 100]}


df = pd.DataFrame(data)

sess = get_or_create_session()

with sess.logger(dataset_name="my_dataset") as logger:
    logger.log_dataframe(df, segments=["col2", "col3"])
    prof_seg = logger.segmented_profiles


for k, prof in prof_seg.items():
    print(prof.tags)
```

We have the following output:

```
WARN: Missing config
{'whylogs.tag.col2': '1', 'whylogs.tag.col3': '100', 'name': 'my_dataset'}
{'whylogs.tag.col2': '1', 'whylogs.tag.col3': '200', 'name': 'my_dataset'}
{'whylogs.tag.col2': '2', 'whylogs.tag.col3': '100', 'name': 'my_dataset'}
```

**Comment by FelipeAdachi** [comment]
Fixed with https://github.com/whylabs/whylogs/commit/1a79f1fc017bb0285afe5cb2dc0184c5f456d677
