### ISSUE TITLE
Autobump workflow on release fails with git working directory not clean

### ISSUE THREAD

**Issue by jamie256** [whylabs/whylogs#722]
## Description

Error copied below from https://github.com/whylabs/whylogs/runs/7641287610?check_suite_focus=true#step:8:50
```
Run # from refs/tags/v[1](https://github.com/whylabs/whylogs/runs/7641287610?check_suite_focus=true#step:8:1).2.3 get 1.2.3
1.0.9
Reading config file .bumpversion.cfg:
[bumpversion]
current_version = 1.0.8
tag = False
parse = (?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)(\-(?P<release>[a-z]+)(?P<build>\d+))?
serialize =
	{major}.{minor}.{patch}-{release}{build}
	{major}.{minor}.{patch}

[bumpversion:part:release]
optional_value = prod
first_value = dev
values =
	dev
	prod

[bumpversion:file:src/whylogs/_version.py]
search = __version__ = "{current_version}"
replace = __version__ = "{new_version}"

[bumpversion:file:docs/conf.py]
search = version = "{current_version}"
replace = version = "{new_version}"

[bumpversion:file:Makefile]
search = version := {current_version}
replace = version := {new_version}

[bumpversion:file:pyproject.toml]
search = version = "{current_version}"
replace = version = "{new_version}"

Attempting to increment part 'patch'
Values are now: build=0, major=1, minor=0, patch=9, release=dev
New version will be '1.0.9'
Git working directory is not clean:
M python/examples/integrations/flask_streaming/.dockerignore

Use --allow-dirty to override this if you know what you're doing.
Traceback (most recent call last):
  File "/home/runner/work/whylogs/whylogs/python/.venv/bin/bump2version", line 8, in <module>
    sys.exit(main())
  File "/home/runner/work/whylogs/whylogs/python/.venv/lib/python3.8/site-packages/bumpversion/cli.py", line 1[18](https://github.com/whylabs/whylogs/runs/7641287610?check_suite_focus=true#step:8:19), in main
    vcs = _determine_vcs_dirty(VCS, defaults)
  File "/home/runner/work/whylogs/whylogs/python/.venv/lib/python3.8/site-packages/bumpversion/cli.py", line [59](https://github.com/whylabs/whylogs/runs/7641287610?check_suite_focus=true#step:8:60)7, in _determine_vcs_dirty
    vcs.assert_nondirty()
  File "/home/runner/work/whylogs/whylogs/python/.venv/lib/python3.8/site-packages/bumpversion/vcs.py", line 76, in assert_nondirty
    raise WorkingDirectoryIsDirtyException(
bumpversion.exceptions.WorkingDirectoryIsDirtyException: Git working directory is not clean:
M python/examples/integrations/flask_streaming/.dockerignore
Error: Process completed with exit code 1.
```

**Comment by jamie256** [comment]
resolved with https://github.com/whylabs/whylogs/commit/d0f5f345a544b369ff5d54bba2db7f6e0f1b275f
