### ISSUE TITLE
Calling `to_pandas` on an empty profile throws

### ISSUE THREAD

**Issue by naddeoa** [whylabs/whylogs#864]
## Description

```python
from whylogs.core import DatasetProfile, DatasetProfileView
profile = DatasetProfile().view()
profile.to_pandas()
```

Gives you this error

```

Traceback (most recent call last):
  File "foo.py", line 13, in <module>
    print(str(profile.to_pandas()))
  File "/home/anthony/.cache/pypoetry/virtualenvs/hello-ray-O1YdFran-py3.8/lib/python3.8/site-packages/whylogs/core/view/dataset_profile_view.py", line 291, in to_pandas
    return df.set_index("column")
  File "/home/anthony/.cache/pypoetry/virtualenvs/hello-ray-O1YdFran-py3.8/lib/python3.8/site-packages/pandas/util/_decorators.py", line 317, in wrapper
    return func(*args, **kwargs)
  File "/home/anthony/.cache/pypoetry/virtualenvs/hello-ray-O1YdFran-py3.8/lib/python3.8/site-packages/pandas/core/frame.py", line 6004, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['column'] are in the columns"
```

## Suggestions
This should probably just be a pandas data frame with the appropriate columns and no data.

## Related

Relates to organization/repo#number 

- [x] I have reviewed the [Guidelines for Contributing](https://github.com/whylabs/whylogs/blob/mainline/.github/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/whylabs/whylogs/blob/mainline/.github/CODE_OF_CONDUCT.md).

**Comment by jamie256** [comment]
In this scenario we haven't seen any columns, so the output would be something like an empty dataframe or None, but we shouldn't hit that KeyError.
