### ISSUE TITLE
Stacktrace at the end of the unit test

### ISSUE THREAD

**Issue by andyndang** [whylabs/whylogs#88]
See: https://github.com/whylabs/whylogs-python/pull/87/checks?check_run_id=1329517256
```
============================= 136 passed in 3.26s ==============================
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/mlflow/__init__.py", line 32, in <module>
    import mlflow.tracking._model_registry.fluent
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/mlflow/tracking/__init__.py", line 8, in <module>
    from mlflow.tracking.client import MlflowClient
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/mlflow/tracking/client.py", line 8, in <module>
    from mlflow.entities import ViewType
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/mlflow/entities/__init__.py", line 6, in <module>
    from mlflow.entities.experiment import Experiment
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/mlflow/entities/experiment.py", line 2, in <module>
    from mlflow.entities.experiment_tag import ExperimentTag
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/mlflow/entities/experiment_tag.py", line 2, in <module>
    from mlflow.protos.service_pb2 import ExperimentTag as ProtoExperimentTag
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/mlflow/protos/service_pb2.py", line 18, in <module>
    from .scalapb import scalapb_pb2 as scalapb_dot_scalapb__pb2
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/mlflow/protos/scalapb/scalapb_pb2.py", line 15, in <module>
    from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/google/protobuf/descriptor_pb2.py", line 1912, in <module>
    '__module__' : 'google.protobuf.descriptor_pb2'
TypeError: A Message class can only inherit from Message
```

**Comment by andyndang** [comment]
Doesn't seem like it's happening anymore. Not sure what fixed the issue
