### ISSUE TITLE
Cannot track a null item

### ISSUE THREAD

**Issue by ibackus** [whylabs/whylogs#89]
We cannot track a `None` item with the standard `DatasetProfile.track()` interface.

This code succeeds:
```python
In [7]: from whylogs import DatasetProfile
   ...: prof = DatasetProfile("name")
   ...: prof.track("column_name", 1)
```

But this code fails:

```python
In [6]: from whylogs import DatasetProfile
   ...: prof = DatasetProfile("name")
   ...: prof.track("column_name", None)
   ...:
[autoreload of whylogs.core.datasetprofile failed: Traceback (most recent call last):
  File "/Users/ibackus/miniconda3/envs/whylogs/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/Users/ibackus/miniconda3/envs/whylogs/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 394, in superreload
    module = reload(module)
  File "/Users/ibackus/miniconda3/envs/whylogs/lib/python3.7/imp.py", line 314, in reload
    return importlib.reload(module)
  File "/Users/ibackus/miniconda3/envs/whylogs/lib/python3.7/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 630, in _exec
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/ibackus/src/whylogs-github/src/whylogs/core/datasetprofile.py", line 780, in <module>
    prof.track("column_name", None)
  File "/Users/ibackus/src/whylogs-github/src/whylogs/core/datasetprofile.py", line 176, in track
    for column_name, data in columns.items():
AttributeError: 'str' object has no attribute 'items'
]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-f6c1e172475f> in <module>
      1 from whylogs import DatasetProfile
      2 prof = DatasetProfile("name")
----> 3 prof.track("column_name", None)

~/src/whylogs-github/src/whylogs/core/datasetprofile.py in track(self, columns, data)
    174             self.track_datum(columns, data)
    175         else:
--> 176             for column_name, data in columns.items():
    177                 self.track_datum(column_name, data)
    178

AttributeError: 'str' object has no attribute 'items'
```

**Comment by lalmei** [comment]
merged in #117
