### ISSUE TITLE
Can't log without pandas available on the environment

### ISSUE THREAD

**Issue by murilommen** [whylabs/whylogs#929]
## Description

When calling `why.log()` an error is thrown if pandas isn't installed.

- System info
  - Operating system and version: macOS / python 3.10.6
- Steps to reproduce:

```bash
pip install whylogs
```

```python
import whylogs as why
why.log(row={"a": [1,2]})
```

Stacktrace:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/murilomendonca/Documents/repos/profile-store-service/.venv/lib/python3.10/site-packages/whylogs/api/logger/__init__.py", line 23, in log
    return TransientLogger(schema=schema).log(obj, pandas=pandas, row=row)
  File "/Users/murilomendonca/Documents/repos/profile-store-service/.venv/lib/python3.10/site-packages/whylogs/api/logger/logger.py", line 84, in log
    prof.track(obj, pandas=pandas, row=row)
  File "/Users/murilomendonca/Documents/repos/profile-store-service/.venv/lib/python3.10/site-packages/whylogs/core/dataset_profile.py", line 113, in track
    self._do_track(obj, pandas=pandas, row=row)
  File "/Users/murilomendonca/Documents/repos/profile-store-service/.venv/lib/python3.10/site-packages/whylogs/core/dataset_profile.py", line 132, in _do_track
    self._initialize_new_columns(tuple(new_cols))
  File "/Users/murilomendonca/Documents/repos/profile-store-service/.venv/lib/python3.10/site-packages/whylogs/core/dataset_profile.py", line 240, in _initialize_new_columns
    self._columns[col] = ColumnProfile(name=col, schema=col_schema, cache_size=self._schema.cache_size)
  File "/Users/murilomendonca/Documents/repos/profile-store-service/.venv/lib/python3.10/site-packages/whylogs/core/column_profile.py", line 19, in __init__
    self._metrics = schema.get_metrics(name)
  File "/Users/murilomendonca/Documents/repos/profile-store-service/.venv/lib/python3.10/site-packages/whylogs/core/schema.py", line 183, in get_metrics
    return self.resolver.resolve(name=name, why_type=self.type_mapper(self.dtype), column_schema=self)
  File "/Users/murilomendonca/Documents/repos/profile-store-service/.venv/lib/python3.10/site-packages/whylogs/core/datatypes.py", line 143, in __call__
    if clz.match(dtype_or_type):  # type: ignore
  File "/Users/murilomendonca/Documents/repos/profile-store-service/.venv/lib/python3.10/site-packages/whylogs/core/datatypes.py", line 32, in match
    return cls._do_match(dtype_or_type, maybe_type)
  File "/Users/murilomendonca/Documents/repos/profile-store-service/.venv/lib/python3.10/site-packages/whylogs/core/datatypes.py", line 57, in _do_match
    if issubclass(dtype_or_type, (bool, int, np.number, np.bool_)):
AttributeError: 'NumpyStub' object has no attribute 'bool_'
```

And after running
```bash
pip install numpy
```

```python
>>> import whylogs as why
>>> why.log(row={"a": [1,2]})

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/murilomendonca/Documents/repos/profile-store-service/.venv/lib/python3.10/site-packages/whylogs/api/logger/__init__.py", line 23, in log
    return TransientLogger(schema=schema).log(obj, pandas=pandas, row=row)
  File "/Users/murilomendonca/Documents/repos/profile-store-service/.venv/lib/python3.10/site-packages/whylogs/api/logger/logger.py", line 84, in log
    prof.track(obj, pandas=pandas, row=row)
  File "/Users/murilomendonca/Documents/repos/profile-store-service/.venv/lib/python3.10/site-packages/whylogs/core/dataset_profile.py", line 113, in track
    self._do_track(obj, pandas=pandas, row=row)
  File "/Users/murilomendonca/Documents/repos/profile-store-service/.venv/lib/python3.10/site-packages/whylogs/core/dataset_profile.py", line 145, in _do_track
    self._columns[k].track_column([row[k]])
  File "/Users/murilomendonca/Documents/repos/profile-store-service/.venv/lib/python3.10/site-packages/whylogs/core/column_profile.py", line 53, in track_column
    ex_col = PreprocessedColumn.apply(series)
  File "/Users/murilomendonca/Documents/repos/profile-store-service/.venv/lib/python3.10/site-packages/whylogs/core/preprocessing.py", line 192, in apply
    return PreprocessedColumn.apply(pd.Series(data, dtype="object"))
TypeError: _StubClass() takes no arguments
```
Finally, with pandas available
```python
>>> import whylogs as why
>>> why.log(row={"a": [1,2]})
<whylogs.api.logger.result_set.ProfileResultSet object at 0x105051210>
```

## Suggestions

Fix and add an env without pandas to test this behavior

- [x] I have reviewed the [Guidelines for Contributing](https://github.com/whylabs/whylogs/blob/mainline/.github/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/whylabs/whylogs/blob/mainline/.github/CODE_OF_CONDUCT.md).

**Comment by jamie256** [comment]
Thanks for the details, I broke the first check by adding np.bool_ check, I'll fix this and add a smoke test to cover. Will have to check if we can run the smoke tests so that they catch the case where extras and optional dependencies are required in core logging scenarios.
